
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import org.json.JSONObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author pro
 */
public class CourseSearch extends java.awt.Frame {

    /**
     * Creates new form CourseSearch
     */
    public CourseSearch() {
        initComponents();
        setSize(400, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        t1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        t2 = new java.awt.TextField();
        label3 = new java.awt.Label();
        t3 = new java.awt.TextField();
        label4 = new java.awt.Label();
        t4 = new java.awt.TextField();
        label5 = new java.awt.Label();
        t5 = new java.awt.TextField();
        button1 = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setText("Code");
        add(label1);
        label1.setBounds(50, 50, 34, 20);
        add(t1);
        t1.setBounds(140, 50, 150, 20);

        label2.setText("Title");
        add(label2);
        label2.setBounds(50, 80, 27, 20);
        add(t2);
        t2.setBounds(140, 80, 150, 20);

        label3.setText("Subject");
        add(label3);
        label3.setBounds(50, 110, 50, 20);
        add(t3);
        t3.setBounds(140, 110, 150, 20);

        label4.setText("Duration");
        add(label4);
        label4.setBounds(50, 140, 60, 20);
        add(t4);
        t4.setBounds(140, 140, 150, 20);

        label5.setText("Fees");
        add(label5);
        label5.setBounds(50, 170, 32, 20);
        add(t5);
        t5.setBounds(140, 170, 150, 20);

        button1.setLabel("Search");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(310, 50, 55, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        try {
            String code=t1.getText();
            String endPoint = "http://localhost:8084/FirstWebService/webapi/course/json/"+code;
            URL url = new URL(endPoint);
            URLConnection con = url.openConnection();
            InputStream is = con.getInputStream();
            BufferedReader br = new BufferedReader(
                    new InputStreamReader(is));
            String output = "", response = "";
            while ((output = br.readLine()) != null) {
                response = response + output;
            }
            System.out.println(response);
            
            JSONObject json=new JSONObject(response);
            
            String v1=String.valueOf(json.getInt("code"));
            String v2=json.getString("title");
            String v3=json.getString("subject");
            String v4=String.valueOf(json.getInt("duration"));
            String v5=String.valueOf(json.getInt("fees"));
            
            t2.setText(v2); t3.setText(v3);
            t4.setText(v4); t5.setText(v5);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseSearch().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    private java.awt.TextField t3;
    private java.awt.TextField t4;
    private java.awt.TextField t5;
    // End of variables declaration//GEN-END:variables
}
